### ISSUE TITLE
Use of separate entities for charging state at card config level

### ISSUE THREAD

**Issue by CDRX2** [maxwroc/battery-state-card#314] opened 2021-08-23 19:17 UTC
Using a secondary entity for charging state is already possible at the individual entity level. However, this feature is not yet applicable at a card config level.

I suppose having something similar to the filter function but for charging state could be a possible approach.

**Comment by CDRX2** [comment] 2021-12-20 13:59
I would imagine something like this:
```
charging_filter:
  include: # filters for auto-adding charging states
    - name: entity_id # entities which id ends with "_is_charging"
      value: "*_is_charging"
```

**Comment by bcutter** [comment] 2022-01-23 15:25
Exactly what I'm looking for. Please have a look at https://community.home-assistant.io/t/lovelace-battery-state-card/191535/157 for potential additional/helpful information.

**Comment by maxwroc** [comment] 2023-10-21 23:19
Closing as a dupe of #365

**Closed by maxwroc** 2023-10-21 23:19 UTC
Labels: enhancement
