### ISSUE TITLE
Please add automatic fill enteties by device_class filter. like an auto-entity mod

### ISSUE THREAD

**Issue by fosterym** [maxwroc/battery-state-card#32] opened 2020-05-02 18:09 UTC
Please add automatic fill enteties by device_class filter. like an auto-entity mod

card:
  show_header_toggle: false
  title: Batteries
  type: entities
filter:
  exclude:
    - name: '*phone*'
    - name: '*iPad*'
  include:
    - attributes:
        device_class: battery
sort:
  count: 7
  method: state
  numeric: true
type: 'custom:auto-entities'

**Comment by maxwroc** [comment] 2020-05-02 18:33
Dupe of #1

**Closed by maxwroc** 2020-05-02 18:33 UTC
Labels: enhancement
