### ISSUE TITLE
Filter include with wildcard (*) doesn't work always.

### ISSUE THREAD

**Issue by Tozzi89** [maxwroc/battery-state-card#633] opened 2024-01-07 21:25 UTC
Version 3.1.1 and 3.0.1 tested.

**Describe the bug**

I'm using the filter options for it to add all my devices with "battery" in the entity id name, but the * doesn't always work;

filter:
  include:
    - name: entity_id
      value: '*_battery_level'
    - name: attributes.device_class
      value: battery

This will show all devices where entity ends with "_battery_level"

But if I change filter to:

filter:
  include:
    - name: entity_id
      value: '*_battery'
    - name: attributes.device_class
      value: battery

I expect to see my other devices that just ends with "_battery", for example: sensor.temp_utomhus_battery

I get just blank, nothing shows up. I have tried to add multiple entities like this:

filter:
  include:
    - name: entity_id
      value: '*_battery_level'
    - name: entity_id
      value: '*_battery'
    - name: attributes.device_class
      value: battery

And it then shows nothing, not even the ones with "battery_level" in name.

# please paste here your card config

type: custom:battery-state-card
title: Battery states
secondary_info: '{last_changed}'
filter:
  include:
    - name: entity_id
      value: '*_battery_level'
    - name: entity_id
      value: '*_battery'
    - name: attributes.device_class
      value: battery
sort:
  by: state
collapse: 8
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true

**Version**

3.1.1.

Even tested with 3.0.1 but same result.

This is a new install for me, trying to set it up for the first time.

**Comment by adix992** [comment] 2024-01-08 02:17
Experiencing same problem

**Comment by maxwroc** [comment] 2024-01-08 06:03
I'm confused TBH. In the title you are saying that the wildcard doesn't work but in the pasted config you don't have the wildcard char:
![image](https://github.com/maxwroc/battery-state-card/assets/8268674/5d649457-82d4-42e7-b492-4437cc302741)

**Comment by peterthepeter** [comment] 2024-01-08 14:20
I have the same Problem, i see only some Battery Items:

![Bildschirmfoto 2024-01-08 um 15 19 11](https://github.com/maxwroc/battery-state-card/assets/74273835/614da17c-d7cc-41b7-91cc-ca749ad8a21f)

if i add

`  include:
    - name: "attributes.device_class"
      value: "battery"`

the card gets complete empty.

**Comment by maxwroc** [comment] 2024-01-08 14:33
Please give an example entity id from your HA which you expect to be matched with for example *_battery_level and which doesn't show up.

There is the other big with sitting. Check if you see more entities when you remove the sort option from config

**Comment by peterthepeter** [comment] 2024-01-08 14:47
Yes the Problem is:

sort:
  by: "state"

if i remove it, it works.
![Bildschirmfoto 2024-01-08 um 15 46 58](https://github.com/maxwroc/battery-state-card/assets/74273835/a696492c-ed69-46d8-b861-bc006b8f2cd1)

**Comment by maxwroc** [comment] 2024-01-08 21:23
Ok so this seems to be the same issue as #630. Please check for the updates there. Closing this on

**Closed by maxwroc** 2024-01-08 21:23 UTC
Labels: bug, details needed
