### ISSUE TITLE
Collapse function doesn't work on Firefox (Windows) and Safari (iOS)

### ISSUE THREAD

**Issue by LarsVenema95** [maxwroc/battery-state-card#115] opened 2020-08-11 10:13 UTC
**Describe the bug**

Collapse function does not work on Firefox (latest version) on Windows 10 and iOS (latest version). 

**How to reproduce**

Configure with collapse option and use Safari browser on iOS.
Also got the same issue on Firefox (latest version) on Windows

**Expected behavior**

Should be a button to collapse. But there is only a "<" icon with a checkbox. 
I don't have this issue at Chrome. 

**YAML configuration**
```yaml

      - type: custom:battery-state-card
        style: |
         ha-card {
          margin: 0px 14px -5px 14px;
          }
        sort_by_level: "asc"
        collapse: 2
        entities:
        - entity: sensor.netatmo_binnenmodule_kamer_battery_percent
          name: "Batterij Netatmo slaapkamer"
        - entity: sensor.netatmo_buitenmodule_battery_percent
          name: "Batterij Netatmo temperatuurmeter buiten" 
        - entity: sensor.netatmo_windmeter_battery_percent
          name: "Batterij Netatmo windmeter"

```

**Screenshots**

![Knipsel](https://user-images.githubusercontent.com/60480515/89885156-e9c37900-dbca-11ea-86b4-b2ba263ef91b.PNG)

**Version**

1.4.1.

**Comment by maxwroc** [comment] 2020-08-17 21:09
TBH when I read the title I was happy as I thought it will be easy to repro and debug this issue for me because of Firefox/Win10 but on the v79 it works perfectly fine for me.

Closing as dupe of #84

**Closed by maxwroc** 2020-08-17 21:09 UTC
Labels: bug
