### ISSUE TITLE
Converting float values to numeric values

### ISSUE THREAD

**Issue by syphernl** [maxwroc/battery-state-card#363] opened 2021-12-30 14:52 UTC
**Is your feature request related to a problem? Please describe.**

Some devices are reported into HASS as a float (e.g. `75.0`) while others are reported as an numeric value (e.g. `75`).  
For most sensors, there are never specific values (e.g. `75,5` or `75,23`)

I have tried to set `round: 0` but this did not make any difference. 

**Describe the solution you'd like**
It would be nice if this card could convert these float values to numeric values instead (or the other way around, for those who prefer that).

**Additional context**
![image](https://user-images.githubusercontent.com/639906/147761937-31d94d6f-5b64-47aa-8fd0-3c22609bd7a1.png)

**Comment by maxwroc** [comment] 2021-12-30 15:39
Dupe of #184 

This will be available in v2.1.0

**Closed by maxwroc** 2021-12-30 15:39 UTC
Labels: enhancement
