### ISSUE TITLE
Support "common options" in filters

### ISSUE THREAD

**Issue by Kilowatt-W** [maxwroc/battery-state-card#448] opened 2022-05-29 11:46 UTC
It looks like in filters the multiplier is not working.

I added some wifi strength values from my esphome development and these are all in -xx dBm. Because the colors are not working with negative values I would like to multipy with -1 to get some positive values.

```
filter:
  include:
    - name: entity_id
      value: '*signal*'
      multiplier: -1
```
Version in use is 2.1.1

Maybe I missed something and there is a way to use colors in reverse mode so 1 is the most ~ green and 100 is worst ~ red ? Maybe this would be a nice feature request :-)

Thank you for this wonderful peace of software.

**Comment by maxwroc** [comment] 2022-05-29 12:22
You cannot take any random property and place it in the other random location ;)

https://github.com/maxwroc/battery-state-card#filter-object

Filter object doesn't have/support the `multiplier` property. So it is not a bug but it make sense to have such functionality so I'm changing the issue type to `enhancement`. Actually if I remember correctly people were asking about something like that in the past.

The only solution which you have now is to list explicitly the entities for which you want to apply/specify multiplier. List them in the `entities` collection of the card.

**Comment by Kilowatt-W** [comment] 2022-05-30 06:42
Thank you for correcting. I think this would be a great feature.

Do you have an idea how to handle negative values in the color gradient ? Something like reverse logic would be nice ? maybe a addon switch like color-gradiant-reverse : true, so it would be possible to make a scale for dbm which are always negative ?

Greetings from Austria
KW

**Comment by maxwroc** [comment] 2022-05-30 10:21
I think gradient won't work with negative values but thresholds should

**Comment by nabahr** [comment] 2022-06-29 20:26
I would also love to see this enhancement, except my use case is to change the attribute on filter entities. 
This card works great for me to show wifi and zigbee connection quality, except many zigbee devices also have a battery attribute so to select the linkquality specifically I have had to list each entity individually as stated above.

**Comment by Ulrar** [comment] 2022-10-08 16:51
I'd love to have it just to add a tap action.
Right now when the filter grabs some weird broken entity I have to try and find it in my entities, it'd be great to be able to just tap it to get the more info menu

**Comment by maxwroc** [comment] 2023-10-22 21:44
@Kilowatt-W showing the dbm via this card will be feasible in version 3.0.0

https://github.com/maxwroc/battery-state-card#other-use-cases

The other questions in this issue are not related to the subject so closing

**Closed by maxwroc** 2023-10-22 21:44 UTC
Labels: enhancement
