### ISSUE TITLE
After Upgrade to 3.1.1 no values by attributes

### ISSUE THREAD

**Issue by CrazyUs3r** [maxwroc/battery-state-card#631] opened 2024-01-05 13:26 UTC
Moin seit dem update funktioniert keine attribute mehr.

Hier nur ein Beispiel was nicht mehr läuft. Zeigt nichts an

type: custom:battery-state-card
title: Luftfeuchtigkeit
secondary_info: '{last_changed}'
icon: mdi:water-percent
filter:
  include:
    - name: attributes.device_class
      value: humidity
sort:
  by: state
collapse: 8
value_override: '{state|abs()}'
colors:
  steps:
    - color: '#00ff00'
      value: 30
    - color: '#ffff00'
      value: 50
    - color: '#ff0000'
      value: 80
  gradient: true

**Comment by jcarlier** [comment] 2024-01-06 09:23
same for me  no results with 👍 

type: custom:battery-state-card
secondary_info: "{last_changed}"
filter:
  include:
    - name: "attributes.device_class"
      value: "battery"
sort:
  by: "state"
collapse: 8
bulk_rename:
  - from: " Battery"
  - from: " level"
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true

ok with  entities

**Comment by bcutter** [comment] 2024-01-06 16:54
Duplicate of https://github.com/maxwroc/battery-state-card/issues/623 (same root cause / core issue)

**Comment by hellcry37** [comment] 2024-01-06 16:55
yah with 3.11 this fails to show anything.

```txt
type: custom:battery-state-card
title: Battery charge remaining
secondary_info: "{last_changed}"
filter:
  include:
    - name: attributes.device_class
      value: battery
  exclude:
    - name: entity_id
      value: '*_battery_low'
    - name: entity_id
      value: sensor.oneplus*battery_level
    - name: entity_id
      value: sensor.pixel*battery_level
sort:
  by: state
collapse: 6
colors:
  steps:
    - '#d9ead3'
    - '#b6d7a8'
    - '#93c47d'
    - '#6aa84f'
  gradient: true
```

**Comment by CrazyUs3r** [comment] 2024-01-06 17:32
I try Tomorrow or i go back to 3.1.0

**Closed** 2024-01-08 06:17 UTC
Labels: bug
