### ISSUE TITLE
Secondary_info processed differently depending on client

### ISSUE THREAD

**Issue by JelleKoster** [maxwroc/battery-state-card#326] opened 2021-10-17 20:02 UTC
**Describe what is wrong**
In Firefox (on win10), the secondary_info can display the value of an attribute (on the same entity).  This is the expected behaviour.
In Chrome (on win10),  it does not display anything with this value (it does if I replace the attribute with a double-quoted string)
In Fully Kiosk (on android 10), it gives a strange value of 87762 weeks ago.

Based on the documentation: _"Secondary info text. It can be a custom text, **attribute name** or state property name e.g. charging, last_changed, "My battery". (example)"_
I expect my use case should work.

**YAML configuration**
```  
- entity: sensor.myVolksWagen_soc
    name: Wolkje
    secondary_info: TotalRangeKm
```

**Screenshot**
FF: ![image](https://user-images.githubusercontent.com/64791840/137642939-8a613cea-b210-4829-8f71-f11dd9b14bd9.png)
Chrome: ![image](https://user-images.githubusercontent.com/64791840/137642971-2c63596c-7a96-4a96-99c0-0836c0d13cee.png)

**Version**
v1.6.4

Thanks in advance for your time.

**Comment by maxwroc** [comment] 2021-12-20 11:05
FYI: I'm about to release v2.0.0 in which a lot of code was rewritten. I hope that this issue will be fixed. I couldn't reproduce it anywhere so I'm not able to confirm it myself.

Once the v2 is released I will close this issue. Feel free to reopen it if the problem is still there

**Comment by JelleKoster** [comment] 2021-12-20 12:29
Thanks Max, I appreciate the notice and agree with closure.

Op ma 20 dec. 2021 12:05 schreef Max Chodorowski ***@***.***>:

**Closed** 2021-12-21 10:16 UTC
Labels: bug, resolved
