### ISSUE TITLE
Charging State

### ISSUE THREAD

**Issue by dartymath** [maxwroc/battery-state-card#97] opened 2020-07-06 10:27 UTC
**Describe the bug**

**How to reproduce**

**Expected behavior**

**YAML configuration**
```yaml

# please paste here your card config

```

**Screenshots**

**Version**

**Comment by dartymath** [comment] 2020-07-06 10:30
Dear All,

I have an issue to get charging state icon when the mobile is plugged !

<img width="752" alt="charging" src="https://user-images.githubusercontent.com/65859148/86583912-50c69000-bf84-11ea-86b2-4335854fee68.PNG">

the attribute is good as show on the secondary_info text !

have you an idea to get same icon as presented on your cards

Thanks

**Comment by maxwroc** [comment] 2020-07-06 10:41
It looks like attribute is a string not a boolean value so in your config you should have `value: "True"`

**Comment by dartymath** [comment] 2020-07-06 12:39
It's works, thanks for the fast answer !

**Comment by dartymath** [comment] 2020-07-06 13:31
Sorry, now it's works but if i use an auto entry include filter and if the entity didn't have this battery_charging attibute the system put it as True -> Bug ?

<img width="748" alt="charging" src="https://user-images.githubusercontent.com/65859148/86598549-8fb50f80-bf9d-11ea-87ff-93391b2abc54.PNG">

**Comment by maxwroc** [comment] 2020-07-06 14:16
It is by design (this way you can set any custom text as a secondary text). 

The solution in such cases is to list explicitly the entities which have charging state. Similarly what you have for vanessa/william etc. So basically you don't set secondary_info property in the root config but you put it individually for each entity on the entities list.

**Comment by dartymath** [comment] 2020-07-06 14:39
Yes agree for the secondary_info, my issue is more for the charging state where i look on the battery_charging attribute as "True" value but if the entities didn't have this one the Card consider as ok or it will return not ok so no charging icon for those entities !!

**Comment by maxwroc** [comment] 2020-07-06 15:04
Ok I see it now and will take a look

**Comment by maxwroc** [comment] 2020-09-04 22:26
Fixed in v1.4.2

**Closed by maxwroc** 2020-09-04 22:26 UTC
Labels: bug
