### ISSUE TITLE
more-info tap action is broken

### ISSUE THREAD

**Issue by Hypfer** [maxwroc/battery-state-card#149] opened 2020-10-24 15:32 UTC
**Describe the bug**

The more-info tap action is broken

**How to reproduce**

- Define card with single entity
- Set tap action to more-info
- Tap/Click

**Expected behavior**

More-info opens

**YAML configuration**
```yaml
type: 'custom:battery-state-card'
tap_action: more-info
entities:
  - sensor.keychain_beacon_battery

```

**Screenshots**

**Version**

Card Version v1.5.0
Home Assistant 0.116.2

I'm pretty sure that this is caused by this:
https://developers.home-assistant.io/blog/2020/10/02/lazymoreinfo/

**Comment by maxwroc** [comment] 2020-10-24 16:52
I'm pretty sure it is caused by wrong configuration 😉 
https://github.com/maxwroc/battery-state-card#tap-action

Tap action has to be an object not a string:
```yaml
tap_action:
  action: more-info
```

Please let me know if it worked. But please do not close this item. This is a pretty common mistake and I wanted to add support for using string there (but since the previous similar item was closed I've forgotten)

**Comment by Hypfer** [comment] 2020-10-24 18:09
Oh. Yeah that did the trick. Thanks

> Tap action has to be an object not a string

For some reason, I didn't get that, even though those are multiple tables. Maybe _because_ they are?
In any case, it would be very helpful to add an example featuring the tap action.

> I wanted to add support for using string there

Personally, I wouldn't do that. Instead I'd suggest adding an error message if the configuration is invalid.
As of now, there's absolutely no feedback that you're doing something wrong if the tap_action is wrong

**Comment by maxwroc** [comment] 2020-10-24 20:39
I will add an example for sure - when you have added this issue I was looking for the example to paste the link here (and I have realized there isn't any) 

I want to do add the support as this is really common mistake and actually it make things easier - if you are not interested in using other action options

**Comment by maxwroc** [comment] 2020-10-24 21:28
BTW there is a warning in the console:
![image](https://user-images.githubusercontent.com/8268674/97093969-42da6f00-1648-11eb-84f2-d215d62fec50.png)

**Comment by Hypfer** [comment] 2020-10-24 21:30
For some reason, warnings were hidden in my console which is why I didn't notice that

![image](https://user-images.githubusercontent.com/974410/97093995-f2b3da80-1650-11eb-93e2-d3e2869a51fc.png)

**Comment by maxwroc** [comment] 2020-10-24 22:10
![image](https://user-images.githubusercontent.com/8268674/97094268-62bf6200-164b-11eb-8d7d-344f9842f85e.png)

**Closed** 2020-10-24 22:10 UTC
Labels: bug, resolved
