### ISSUE TITLE
Batterie level Aarlo Camera

### ISSUE THREAD

**Issue by feron81** [maxwroc/battery-state-card#632] opened 2024-01-06 08:16 UTC
I have a entity called camera.aarlo_dachterrasse. This is a outdoor camera. Now I would like to show the battery level of this device. It has a lot of under attribute. I need the under attribute "battery_level".

I tried now several things for example: 
- entity: camera.aarlo_dachterrasse

It show me nothing. Do you have an idea, how I have to set the entry for this device. For all other Battery level I have no problem.

Thank you for your help

**Comment by maxwroc** [comment] 2024-01-08 06:22
Try the following:

```yaml
entities:
  - entity: camera.aarlo_dachterrasse
    attribute: "battery_level"
```

**Comment by feron81** [comment] 2024-01-08 08:08
Thank you very much. It's not working. I made it like this. Here print-screens about. Do you have another idea?

![Screenshot 2024-01-08 090657](https://github.com/maxwroc/battery-state-card/assets/84832617/0581dee7-b324-46e9-8a82-3b16c530878b)

![Screenshot 2024-01-08 090242](https://github.com/maxwroc/battery-state-card/assets/84832617/15c6ae3f-a827-4aac-84a9-db03df495460)

![Screenshot 2024-01-08 090343](https://github.com/maxwroc/battery-state-card/assets/84832617/1595ae08-0d37-4653-96c2-6199e42a903d)

**Comment by maxwroc** [comment] 2024-01-08 09:04
Your config looks fine. I need to double check - maybe there is a bug

**Comment by feron81** [comment] 2024-01-08 09:10
It would be great, if you can double check. I also had problem, that the whole Battery state Dashboard are not visible after I added this battery level sensor. It could be that there is a bug.

**Comment by maxwroc** [comment] 2024-01-12 17:55
For me it works although when I modify the configuration in the HA yaml editor I don't see the updated result, It is being applied only when I hit "save card" button.

Please let me know if that is the case for you too

**Comment by feron81** [comment] 2024-01-13 08:21
Hi Max

No, that's not the same case I have. When I add this directly in your "Batter state editor" it's not working and show me nothing.

  - entity: sensor.camera.aarlo_dachterrasse
    attribute: "battery_level"

Best
feron

**Comment by maxwroc** [comment] 2024-01-13 10:55
This is not a valid entity Id: `sensor.camera.aarlo_dachterrasse` and that is why it is not found

**Comment by feron81** [comment] 2024-01-13 10:57
I tried with several entity ID: camera.aarlo_dachterrasse. Here the print-screen I sent you. Whats the right one?

![294841293-1595ae08-0d37-4653-96c2-6199e42a903d](https://github.com/maxwroc/battery-state-card/assets/84832617/70bcdc73-25ee-424c-a80a-fa751f462a15)

**Comment by maxwroc** [comment] 2024-01-13 11:04
Please copy paste the config (as a text not screenshot). There is a plenty of issues where people have typos somewhere and it is easier for me to just try the exact configuration you have.

BTW color_gradient  is not supported any more - please check breaking changes section in the doc and new examples. But this should not be the reason why it doesn't work.

Regarding the entity ID you need to use the exact ID your entity has

Please paste a screenshot of the entire editor pane together with rendered part. Sth like the following
![image](https://github.com/maxwroc/battery-state-card/assets/8268674/a4f6e283-190b-43fe-ab87-5426fdecee27)

In your previous list of screenshots the pasted config doesn't match the pasted result. I'd like to see them both.

**Comment by feron81** [comment] 2024-01-13 11:08
type: custom:battery-state-card
title: Batterie
sort:
  by: state
collapse: 25
entities:
  - entity: sensor.iphone_109_battery_level
  - entity: sensor.whirlpool_batterie
  - entity: sensor.aussenmodul_batterie
  - entity: sensor.buro_batterie
  - entity: sensor.badzimmer_og_batterie
  - entity: sensor.lina_zimmer_batterie
  - entity: sensor.luisa_zimmer_batterie
  - entity: sensor.spielzimmer_batterie
  - entity: sensor.hottli_batterie
  - entity: sensor.keller_batterie
  - entity: sensor.hwr_batterie
  - entity: sensor.regen_batterie
  - entity: sensor.wind_batterie
  - entity: sensor.usv_batterie
  - entity: sensor.hue_sensor_velo_batterie
  - entity: sensor.bewegung_balkon_batterie
  - entity: sensor.sonos_move_battery
  - entity: sensor.hue_buro_wall_modul_batterie
  - entity: sensor.hue_esszimmer_wall_modul_batterie
  - entity: sensor.sonos_roam_batterie
  - entity: camera.aarlo_dachterrasse
    attribute: battery_level

**Comment by feron81** [comment] 2024-01-13 11:09
When I add the camera like this, the dashboard shows me the battery state dashboard not. 

![Screenshot 2024-01-13 120912](https://github.com/maxwroc/battery-state-card/assets/84832617/f6601847-e6a2-428e-8646-a73724ed874d)

**Comment by maxwroc** [comment] 2024-01-13 11:21
Ok, so the card doesn't show up when you have such configuration, correct?

If so there might be a bug - related to similar issues reported earlier (although in the recent releases people confirmed it started working for them again). I will double check

**Comment by feron81** [comment] 2024-01-13 11:25
Yes, then my dashboard shows me nothing. When I delete the Camera entity, the dashboard shows up without problems. And also the dashboard shows me no battery level for the camera in the battery state preview.

**Comment by maxwroc** [comment] 2024-01-13 11:29
Ok this narrows down the search area. If you can confirm whether there is an error in browser console it would be great.

On PC you can press F12 and then select console tab. If there is an error related to the battery-state-card please let me know.

**Comment by feron81** [comment] 2024-01-13 11:32
Maybe here?

![Screenshot 2024-01-13 123219](https://github.com/maxwroc/battery-state-card/assets/84832617/098ea167-e064-49a0-8b8d-b36bd1cf279a)

**Comment by maxwroc** [comment] 2024-01-13 11:36
Hmm I think I have found the culprit but in the lines above - not the ones which the debugger highlights to you.

If you look at the console tab do you see error complaining that the "replace is not a function"?

**Comment by feron81** [comment] 2024-01-13 11:42
![Screenshot 2024-01-13 124136](https://github.com/maxwroc/battery-state-card/assets/84832617/a9af0275-bd58-4175-a6fc-5546e507dacc)

**Comment by feron81** [comment] 2024-01-13 11:42
Here a print-screen from console

**Comment by maxwroc** [comment] 2024-01-13 11:43
Great! Thanks - it is the same thing I have found. Your problem will be fixed in v3.1.4 - I'll release it in couple of min

**Closed by maxwroc** 2024-01-13 11:43 UTC
Labels: bug

**Comment by feron81** [comment] 2024-01-13 12:07
Thank you, that works without problems. Is it possible to comment out one line in the battery state card configuration, so that I can write a comment?

**Comment by maxwroc** [comment] 2024-01-13 13:49
Comments work only in the Lovelace yaml mode config. If you add card via UI app comments are automatically removed
