### ISSUE TITLE
Value-mappings possible?

### ISSUE THREAD

**Issue by emufan** [maxwroc/battery-state-card#520] opened 2023-01-01 18:58 UTC
In my case, I have a voltage range, which I would like to map/convert to %.

As I cannot use `multiplier` in this case, because e.g. 2.1 is 0% and as I want to set it only in 25% steps, this is not working.

`Convert` is not helpful here as well, if I have e.g. numeric values with two digit decimals and e.g. a range between 2.00 and 3.00. This way I would have to define 100 convert mappings. 

Is there a way to define mappings like the  `color_thresholds` but not for color and for a value mapping, like

below/equal to 5 = 100%
below/equal to 2.90 = 75%
below/equal to 2.40 = 50%
below/equal to 2.10 = 0%

I wonder if I have only not seen the documentation or examples, so help if very appreciated.

**Comment by maxwroc** [comment] 2023-01-01 20:09
Sorry, it's not possible.

**Comment by emufan** [comment] 2023-01-01 21:40
What a pity. Not yet or not at all, so no possible to have this in a new feature in the mid or far future?

**Comment by maxwroc** [comment] 2023-01-02 00:55
Depends on the interest. I think this is not so common scenario

**Comment by emufan** [comment] 2023-01-02 07:15
Would love it, as I have a lot of such devices, which are reporting voltage and not battery percentage. And yes, I could define template entities for this, but as these are very lot of devices, I would like to have it only in this great card, where it is the only place, where I would need and use them.

Of course, most probably not a common scenario, but one can use it for the `multiplier`-scenario for more specific definitions as well. to set 0, 100 and other cases.

**Comment by filippo196302** [comment] 2023-06-16 06:31
> In my case, I have a voltage range, which I would like to map/convert to %.
> 
> As I cannot use `multiplier` in this case, because e.g. 2.1 is 0% and as I want to set it only in 25% steps, this is not working.
> 
> `Convert` is not helpful here as well, if I have e.g. numeric values with two digit decimals and e.g. a range between 2.00 and 3.00. This way I would have to define 100 convert mappings.
> 
> Is there a way to define mappings like the `color_thresholds` but not for color and for a value mapping, like
> 
> below/equal to 5 = 100% below/equal to 2.90 = 75% below/equal to 2.40 = 50% below/equal to 2.10 = 0%
> 
> I wonder if I have only not seen the documentation or examples, so help if very appreciated.


I am very interested in this features. Alternatively, the "multiplier" tag could be expanded with more complex functions (templates)

**Comment by igorsantos07** [comment] 2023-10-19 22:57
Seems a dupe of #490 - could be closed to focus comments and development there.

**Comment by maxwroc** [comment] 2023-10-20 03:08
True. Closing.

Thanks

**Closed by maxwroc** 2023-10-20 03:08 UTC
Labels: question
